config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :themes do
    resources :images, only: [ :new, :create ]
  end
  resources :images, only: [ :destroy ]
  resources :contacts, only: [ :new, :create, :index ] do
    member do
      post 'contacted'
    end
  end
  resources :livredors, only: [ :new, :create, :index ]
  resources :articles
end

app/models/animal.rb
class Animal < ApplicationRecord
  has_many :images, dependent: :destroy

  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  has_many_attached :photos

  has_rich_text :rich_body

  validates :title, :rich_body, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :content, presence: true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :theme

  has_one_attached :photo

  validates :description, presence: true
end

app/models/livredor.rb
class Livredor < ApplicationRecord
  validates :name, presence: true
  validates :content, presence: true
end

app/models/theme.rb
class Theme < ApplicationRecord
  belongs_to :user
  has_many :images, dependent: :destroy

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
  has_many :themes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [ :show, :edit, :update, :destroy ]
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      redirect_to article_path(@article)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @article.update(article_params)

    redirect_to article_path(@article)
  end

  def destroy
    @article.destroy

    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :rich_body, photos: [])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [ :contacted ]
  skip_before_action :authenticate_user!, only: [ :new, :create ]

  def index
    @contacts = Contact.all.sort
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.save

    redirect_to root_path
  end

  def contacted
    @contact.contacted = true
    if @contact.save
      render json: { success: true }
    else
      render json: { success: false }, status: :unprocessable_entity
    end
  end

  private

  def set_contact
    @contact = Contact.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:email, :content)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
    before_action :set_image, only: [ :destroy ]

  def new
    @theme  = Theme.find(params[:theme_id])
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    @theme = Theme.find(params[:theme_id])
    @image.theme = @theme
    if @image.save
      redirect_to theme_path(@theme)
    else
      render :new
    end
  end

  def destroy
    @image.destroy
    redirect_to theme_path(@image.theme)
  end

  private

  def set_image
    @image = Image.find(params[:id])
  end

  def image_params
    params.require(:image).permit(:description, :photo)
  end
end

app/controllers/livredors_controller.rb
class LivredorsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :new, :create ]

  def index
    @livredors = Livredor.all
  end

  def new
    @livredor = Livredor.new
  end

  def create
    @livredor = Livredor.new(contact_params)
    @livredor.save

    redirect_to livredors_path
  end

  private

  def contact_params
    params.require(:livredor).permit(:name, :content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :about]

  def home
  end

  def about
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: [ :show, :edit, :update, :destroy ]
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    @themes = Theme.all
  end

  def show
  end

  def new
    @theme = Theme.new
  end

  def create
    @theme = Theme.new(theme_params)
    @theme.user = current_user
    if @theme.save
      redirect_to theme_path(@theme)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @theme.update(theme_params)

    redirect_to theme_path(@theme)
  end

  def destroy
    @theme.destroy

    redirect_to themes_path
  end

  private

  def set_theme
    @theme = Theme.find(params[:id])
  end

  def theme_params
    params.require(:theme).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/animals/edit.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-12 col-sm-8 col-md-4 offset-sm-2 offset-md-4">
      <%= simple_form_for @animal do |f| %>
        <%= f.input :name %>
        <%= f.button :submit, "MODIFIER", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/animals/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 mb-3">
      <div class="liste border-bottom">
        <ul class="list-inline">
          <% @animals.each do |animal| %>
            <%= link_to animal_path(animal) do %>
              <li class="list-inline-item mt-2 mr-3"><%= animal.name %></li>
            <% end %>
          <% end %>
        </ul>
      </div>
      <div class="cards mt-3">
        <% @animals.each do |animal| %>
          <% animal.images.each do |image| %>
            <div data-toggle="modal" data-target="#indexModal">
              <%= cl_image_tag image.photo.key, width: 360, height: 240, crop: :fill %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="indexModal" tabindex="-1" aria-labelledby="indexModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-xl">
    <div class="modal-content">
      <div class="d-flex justify-content-end">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body d-flex justify-content-center">
        <div class="single-item">
          <% @animals.each do |animal| %>
            <% animal.images.each do |image| %>
              <div data-toggle="modal" data-target="#indexModal">
                <%= cl_image_tag image.photo.key, width: 1000, height: 650, crop: :fill %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/animals/new.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-12 col-sm-8 col-md-4 offset-sm-2 offset-md-4">
      <%= simple_form_for(@animal) do |f| %>
        <%= f.input :name %>
        <%= f.button :submit, "CREER UN THEME", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/animals/show.html.erb
<div class="trash">
  <% if user_signed_in? %>
    <div class="showme">
      <%= link_to "Effacer #{@animal.name}",
                  animal_path(@animal),
                  method: :delete,
                  data: {confirm: "Êtes-vous sûr(e)?" } %>
    </div>
  <% end %>
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <% if user_signed_in? %>
          <div class="d-flex justify-content-center border-bottom dropdown">
            <h3 class="mt-2 mb-3 dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= @animal.name %></h3>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
              <%= link_to "AJOUTER PHOTO(S)", new_animal_image_path(@animal), class: "dropdown-item" %>
            </div>
          </div>
        <% else %>
          <div class="border-bottom dropdown d-flex justify-content-center">
            <h3 class="mt-2 mb-3"><%= @animal.name %></h3>
          </div>
        <% end %>
        <div class="cards mt-3">
          <% @animal.images.each do |image| %>
            <div class="d-flex flex-column" data-toggle="modal" data-target="#showModal">
              <%= cl_image_tag image.photo.key, width: 360, height: 240, crop: :fill %>
              <p><%= image.description %></p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="showModal" tabindex="-1" aria-labelledby="showModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-xl">
    <div class="modal-content">
      <div class="d-flex justify-content-end">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body d-flex justify-content-center">
        <div class="single-item">
          <% @animal.images.each do |image| %>
            <div class="d-flex justify-content-center">
              <%= cl_image_tag image.photo.key, width: 1000, height: 650, crop: :fill %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<div class="article-bis">
  <%= simple_form_for(@article) do |f| %>
    <%= f.input :title %>
    <%= f.rich_text_area :rich_body %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.button :submit, "Modifier", class: "btn btn-success" %>
  <% end %>
</div>

app/views/articles/index.html.erb
<div class="article">
  <% @articles.each do |article| %>
    <%= link_to article_path(article) do %>
      <div class="card-product-article mb-3">
        <%= cl_image_tag article.photos.first.key, crop: :fill %>
        <div class="article-info">
          <div class="article-title border-bottom">
            <p class="pl-2 pt-2"><%= article.title %></p>
            <p class="pr-2 pt-2">Publié le <%= article.created_at.to_s.split(" ").first(2).join(" à ") %></p>
          </div>
          <div class="article-rich pl-2 pr-2">
            <div class="article-rich-body">
              <p><%= article.rich_body %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/articles/new.html.erb
<div class="article-bis">
  <%= simple_form_for(@article) do |f| %>
    <%= f.input :title %>
    <%= f.rich_text_area :rich_body %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.button :submit, "Poster", class: "btn btn-success" %>
  <% end %>
</div>

app/views/articles/show.html.erb
<% if user_signed_in? %>
  <div class="d-flex justify-content-between">
    <%= link_to "Effacer",
                article_path(@article),
                method: :delete,
                data: {confirm: "Êtes-vous sûr(e)?" },
                class: "btn btn-danger mt-5" %>
    <%= link_to "Modifier l'article", edit_article_path(@article), class: "btn btn-success mt-5" %>
  </div>
<% end %>
<div class="article-show">
    <div class="article-title border-bottom">
      <p class="flex-grow-1 p-2"><%= @article.title %></p>
      <p class="p-2">Publié le <%= @article.created_at.to_s.split(" ").first(2).join(" à ") %></p>
    </div>
    <div class="p-2">
      <%= @article.rich_body %>
    </div>
    <% if @article.photos.count <= 1 %>
      <div class="article-photo">
        <% @article.photos.each do |photo| %>
          <%= cl_image_tag photo.key, crop: :fill %>
        <% end %>
      </div>
    <% else %>
      <div class="article-photos">
        <% @article.photos.each do |photo| %>
          <%= cl_image_tag photo.key, crop: :fill %>
        <% end %>
      </div>
    <% end %>
</div>

app/views/contacts/index.html.erb
<div class="contact">
  <% @contacts.each do |contact| %>
    <% if contact.contacted == true %>
      <div class="para">
        <input class="form-checkbox" type="checkbox" value="" id="defaultCheck" data-contact-id="<%= contact.id %>">
        <div class="art">
          <p><%= contact.content %></p>
        </div>
        <div class="inf d-flex flex-column justify-content-center">
          <p><%= contact.email %></p>
          <p><%= contact.created_at %></p>
        </div>
      </div>
    <% else %>
      <div class="affiche">
        <input class="form-checkbox" type="checkbox" value="" id="defaultCheck" data-contact-id="<%= contact.id %>">
        <div class="art">
          <p><%= contact.content %></p>
        </div>
        <div class="inf d-flex flex-column justify-content-center">
          <p><%= contact.email %></p>
          <p><%= contact.created_at %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div class="contact-new">
  <div class="question">
    <p>Une photo vous plait?</p>
    <p>Vous souhaitez avoir des renseignements?</p>
    <p>Contactez-moi</p>
  </div>
  <div class="formulaire">
    <%= simple_form_for(@contact) do |f| %>
      <%= f.input :email, :label => 'Votre email' %>
      <%= f.input :content, :label => 'Posez votre question' %>
      <%= f.button :submit, "Envoyer", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/images/new.html.erb
<div class="showi">
  <%= simple_form_for [@theme, @image] do |f| %>
    <%= f.input :photo, as: :file %>
    <%= f.input :description %>
    <%= f.button :submit, "Ajouter photo", class: "btn btn-success" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Patouphoto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/flashes' %>
  </body>
</html>

app/views/livredors/index.html.erb
<div class="livredor d-flex flex-column align-items-center">
  <% @livredors.each do |livredor| %>
    <div class="affichage">
      <p><%= livredor.content %></p>
      <div>
        <p><%= livredor.name %></p>
        <P><%= livredor.created_at %></P>
      </div>
    </div>
  <% end %>
</div>
<div class="lien">
  <%= link_to "LAISSER UN COMMENTAIRE", new_livredor_path, class: "btn btn-success" %>
</div>

app/views/livredors/new.html.erb
<div class="livre d-flex justify-content-center align-items-center">
  <%= simple_form_for(@livredor) do |f| %>
    <%= f.input :name %>
    <%= f.input :content %>
    <%= f.button :submit, "Poster votre commentaire", class: "btn btn-success adap" %>
  <% end %>
</div>

app/views/pages/about.html.erb
<div class="about">
  <div class="card-product">
    <%= image_tag "PROPOS2.jpg", alt: "photo_Patricia" %>
    <div class="card-product-infos">
      <h2>Petit mot de l'artiste</h2>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, eum optio asperiores, maiores sequi molestiae magnam quo nulla. Adipisci, neque!</p>
      <div class="instaface">
        <a href="https://www.instagram.com/patochelou/?hl=fr" target="_blank" ><i class="fab fa-instagram"></i></a>
        <a href="https://www.facebook.com/patricia.beaupuis.7" target="_blank" ><i class="fab fa-facebook"></i></a>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div id="home">
  <div class="titre d-flex border-bottom">
    <%= image_tag "Patochelou Photography logo.png", alt: "app_photo" %>
    <%= link_to new_user_session_path do %>
      <p>.</p>
    <% end %>
    <p>Patochelou</p>
  </div>
  <div class="compteur">
    <a href="http://www.mon-compteur.fr"><img src="http://www.mon-compteur.fr/html_c02genv2-71264-2" border="0" /></a>
    <p>&copy; 2020 Design with <i class="fas fa-heart"></i> by TocTof</p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-patou border-bottom">
  <ul class="d-flex justify-content-around align-items-center">
    <% if user_signed_in? %>
      <li class="nav-item active">
        <%= link_to "ACCUEIL", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "PORTFOLIO", themes_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "BLOG", articles_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "A PROPOS", about_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "appareil_photo.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Ajouter thème", new_theme_path, class: "dropdown-item" %>
          <%= link_to "Ajouter article", new_article_path, class: "dropdown-item" %>
          <%= link_to "Livre d'or", livredors_path, class: "dropdown-item" %>
          <%= link_to "Liste contacts", contacts_path, class: "dropdown-item" %>
          <%= link_to "Deconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to "ACCUEIL", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "PORTFOLIO", themes_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "BLOG", articles_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "A PROPOS", about_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <p class="dropdown-toggle" id="navbarDropdown1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-bars"></i>
        </p>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown1">
          <%= link_to "CONTACT", new_contact_path, class: "dropdown-item" %>
          <%= link_to "LIVRE D'OR", livredors_path, class: "dropdown-item" %>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/themes/edit.html.erb
<div class="formul-new-theme d-flex align-items-center justify-content-center">
  <%= simple_form_for @theme do |f| %>
    <%= f.input :name %>
    <%= f.button :submit, "Modifier", class: "btn btn-success" %>
  <% end %>
</div>

app/views/themes/index.html.erb
<div class="liste border-bottom">
  <ul class="list-inline">
    <% @themes.each do |theme| %>
      <%= link_to theme_path(theme) do %>
        <li class="list-inline-item mt-2 mr-3"><%= theme.name %></li>
      <% end %>
    <% end %>
  </ul>
</div>
<div class="cards mt-3">
  <% image_count = 0 %>
  <% @themes.each do |theme| %>
    <% theme.images.each do |image| %>
      <div class="card d-flex justify-content-center" data-toggle="modal" data-target="#indexModal" data-image-id="<%= image_count %>" >
        <% image_count +=1 %>
        <%= cl_image_tag image.photo.key, crop: :fill %>
      </div>
    <% end %>
  <% end %>
</div>

<div class="modal fade" id="indexModal" tabindex="-1" aria-labelledby="indexModalLabel" aria-hidden="true" >
  <div class="modal-dialog modal-dialog-centered modal-xl">
    <div class="modal-content">
      <div class="d-flex justify-content-end">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body d-flex justify-content-center">
        <div class="single-item" style="opacity: 0;" data-image-id="0">
          <% @themes.each do |theme| %>
            <% theme.images.each do |image| %>
              <div class="relou d-flex justify-content-center">
                <%= cl_image_tag image.photo.key, crop: :fill %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/themes/new.html.erb
<div class="formul-new-theme d-flex align-items-center justify-content-center">
  <%= simple_form_for(@theme) do |f| %>
    <%= f.input :name %>
    <%= f.button :submit, "Créer un thème", class: "btn btn-success" %>
  <% end %>
</div>

app/views/themes/show.html.erb
<% if user_signed_in? %>
  <div class="sho d-flex justify-content-center border-bottom dropdown">
    <h4 class="mt-2 dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= @theme.name %></h3>
    <div class="dropdown-menu dropdown-menu" aria-labelledby="dropdownMenuButton">
      <%= link_to "Modifier nom du thème", edit_theme_path(@theme), class: "dropdown-item" %>
      <%= link_to "Ajouter photo", new_theme_image_path(@theme), class: "dropdown-item" %>
      <%= link_to "Effacer #{@theme.name}",
                  theme_path(@theme),
                  method: :delete,
                  data: {confirm: "Êtes-vous sûr(e)?" },
                  class: "dropdown-item" %>
    </div>
  </div>
<% else %>
  <div class="sho border-bottom d-flex justify-content-center">
    <h3 class="mt-2 mb-3"><%= @theme.name %></h3>
  </div>
<% end %>
<div class="cards mt-3">
  <% image_count = 0 %>
  <% @theme.images.each do |image| %>
    <div class="card d-flex flex-column justify-content-between" data-toggle="modal" data-target="#showModal" data-image-id="<%= image_count %>" >
      <% image_count +=1 %>
      <%= cl_image_tag image.photo.key, crop: :fill %>
      <% if user_signed_in? %>
        <%= link_to "+", image_path(image), method: :delete, data: { confirm: "Are you sure?" }, class: "remove-link" %>
      <% end %>
      <div>
        <p class="p-2"><%= image.description %></p>
      </div>
    </div>
  <% end %>
</div>
<div class="modal fade" id="showModal" tabindex="-1" aria-labelledby="showModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg modal-xl">
    <div class="modal-content">
      <div class="d-flex justify-content-end">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body d-flex justify-content-center">
        <div class="single-item" style="opacity: 0;" data-image-id="0">
          <% @theme.images.each do |image| %>
            <div class="relou d-flex justify-content-center">
              <%= cl_image_tag image.photo.key, crop: :fill %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>